name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Running tests
      run: |
        echo Starting the tests:
        curl https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.11.4/junit-platform-console-standalone-1.11.4.jar -o lib/junit-platform-console-standalone-1.11.4.jar
        curl https://repo1.maven.org/maven2/javax/servlet/javax.servlet-api/3.0.1/javax.servlet-api-3.0.1.jar -o lib/javax.servlet-api-3.0.1.jar
        curl https://repo1.maven.org/maven2/org/jfree/jcommon/1.0.17/jcommon-1.0.17.jar -o lib/jcommon-1.0.17.jar
        javac -d bin -cp "lib/*:bin" $(find src -name "*.java")
        javac -d bin -cp "bin:lib/*" $(find test -name "*.java")
        javac -d bin -cp bin:lib/junit-platform-console-standalone-1.11.4.jar $(find test/org/jfree/data -name "*.java")
        java -jar lib/junit-platform-console-standalone-1.11.4.jar -cp "bin:lib/*" --scan-class-path
